name: CI Workflow with Branch

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Print Hello
      run: echo "Hello, CI Workflow!"

    - name: Determine Branch
      run: echo "On branch ${{ github.ref }}"
    
